import './globals.css'
import { Montserrat } from 'next/font/google'
import { QCLayout } from './qc.layout'

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <QCLayout>
    <html lang="ru">
      <body className={montserrat.className}>{children}</body>
    </html>
    </QCLayout>
  )
}
